# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Murmur3 hash.
#'
#' Relies on murmur3 implementation in `digest` package.
#'
#' @param x a character vector
#' @export
murmur3hash <- function(x) {
    .Call(`_mlvocab_murmur3hash`, x)
}

C_vocab <- function(corpus, oldvocab) {
    .Call(`_mlvocab_C_vocab`, corpus, oldvocab)
}

C_embed_vocab <- function(vocabdf, embeddings, by_row, unknown_buckets, min_to_average) {
    .Call(`_mlvocab_C_embed_vocab`, vocabdf, embeddings, by_row, unknown_buckets, min_to_average)
}

C_corpus2ixseq <- function(corpus, vocabdf, keep_unknown, unknown_buckets, reverse) {
    .Call(`_mlvocab_C_corpus2ixseq`, corpus, vocabdf, keep_unknown, unknown_buckets, reverse)
}

C_corpus2ixmat <- function(corpus, vocabdf, maxlen, pad_right, trunc_right, keep_unknown, unknown_buckets, reverse) {
    .Call(`_mlvocab_C_corpus2ixmat`, corpus, vocabdf, maxlen, pad_right, trunc_right, keep_unknown, unknown_buckets, reverse)
}

C_dtm <- function(corpus, vocabdf, unknown_buckets, output) {
    .Call(`_mlvocab_C_dtm`, corpus, vocabdf, unknown_buckets, output)
}

C_tdm <- function(corpus, vocabdf, unknown_buckets, output) {
    .Call(`_mlvocab_C_tdm`, corpus, vocabdf, unknown_buckets, output)
}

C_is_ascii <- function(vec) {
    .Call(`_mlvocab_C_is_ascii`, vec)
}

